### ISSUE TITLE
All AIMs are A -> C 

### ISSUE THREAD

**Issue by BEFH** [ucfcbb/Recomb-Mix#1]
Is there a reason all of the AIMs in the compact VCFs are A -> C?

**Comment by yuan-webb-wei** [comment]
It was hard-coded. The dataset was simulated using SLiM. The REF and ALT fields in the VCF file are not important to SLiM so their values are always the same in the simulated dataset (http://benhaller.com/slim/SLiM_Manual.pdf#page=738).

I will have their values updated to dot "." to avoid confusion.

**Comment by yuan-webb-wei** [comment]
The files are updated.
