### ISSUE TITLE
Chunking query file for large sample sizes

### ISSUE THREAD

**Issue by BEFH** [ucfcbb/Recomb-Mix#2]
How do you recommend chunking large query files? If the files are split into many sets of samples and results are computed on a per-chromosome basis using the same compact VCF, will the same model be used in each sample set? If we chunk into sub, chromosomal regions, how should that be done to avoid errors on the edges of the chunks?

**Comment by yuan-webb-wei** [comment]
The same model will be used whether the query samples are in one large file or split into multiple files.

Recomb-Mix is a site-based method, so the result should be consistent if the query is run as a whole or chunked into sub-chromosomal regions. It is possible the edge of the chunk is around an ancestry breakpoint, which might affect the result of a few markers at the endpoint. If this is a concern, I would suggest leaving overlaps for each adjacent chunk and discarding the overlap regions when merging the results.
